parameters:
  speerit_airbrake.notifier.class: Airbrake\Notifier
  speerit_airbrake.request_exception_listener.class: Speerit\AirbrakeBundle\EventListener\RequestExceptionListener
  speerit_airbrake.console_exception_listener.class: Speerit\AirbrakeBundle\EventListener\ConsoleExceptionListener
  speerit_airbrake.shutdown_listener.class: Speerit\AirbrakeBundle\EventListener\ShutdownListener

services:
#    speerit_airbrake.example:
#        class: Speerit\AirbrakeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
