parameters:
  ami_airbrake.notifier.class: Airbrake\Notifier
  ami_airbrake.exception_listener.class: Speerit\AirbrakeBundle\EventListener\ExceptionListener
  ami_airbrake.shutdown_listener.class: Speerit\AirbrakeBundle\EventListener\ShutdownListener

services:
#    speerit_airbrake.example:
#        class: Speerit\AirbrakeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
