language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*

install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer install

script:
  - phpunit
  - vendor/bin/phpcs -n -p --encoding=utf-8 --standard=PSR2 --extensions=php --ignore=vendor .
